include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/intl/*"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore
    implementation_imports: ignore
    
linter:
  rules:
