// Mocks generated by Mockito 5.0.15 from annotations
// in flutter_recruitment_task/test/mocks/common.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_recruitment_task/models/movie.dart' as _i7;
import 'package:flutter_recruitment_task/models/movie_list.dart' as _i5;
import 'package:flutter_recruitment_task/services/api_service.dart' as _i3;
import 'package:flutter_recruitment_task/utils/errors.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setLanguage(String? code) =>
      super.noSuchMethod(Invocation.method(#setLanguage, [code]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<_i2.Either<_i5.MovieList, _i6.AppError>> searchMovies(
          String? query, int? page) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query, page]),
          returnValue: Future<_i2.Either<_i5.MovieList, _i6.AppError>>.value(
              _FakeEither_0<_i5.MovieList, _i6.AppError>())) as _i4
          .Future<_i2.Either<_i5.MovieList, _i6.AppError>>);
  @override
  _i4.Future<_i2.Either<_i7.Movie, _i6.AppError>> getMovieDetails(
          int? movieId) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetails, [movieId]),
              returnValue: Future<_i2.Either<_i7.Movie, _i6.AppError>>.value(
                  _FakeEither_0<_i7.Movie, _i6.AppError>()))
          as _i4.Future<_i2.Either<_i7.Movie, _i6.AppError>>);
  @override
  String toString() => super.toString();
}
